# Generated by Django 3.1.1 on 2021-01-02 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('cod_comunidad', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom_comunidad', models.CharField(max_length=100, verbose_name='Nombre de la comunidad')),
                ('descrip', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripcion')),
                ('fecha_creacion', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de creacion')),
                ('hubi_comuni', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hubicacion de la Comunidad ')),
                ('coor_comuni', models.CharField(blank=True, max_length=100, null=True, verbose_name='Coordenadas para google maps')),
                ('image_co', models.ImageField(blank=True, default='static/img/Comunidad-online.png', null=True, upload_to='static/img', verbose_name='Imagen de referencia')),
                ('is_active', models.BooleanField(default=False, verbose_name='¿Esta activo?')),
            ],
        ),
        migrations.CreateModel(
            name='data',
            fields=[
                ('id_data', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_add', models.DateField(auto_now_add=True)),
                ('cant_usuarios', models.IntegerField()),
                ('cant_nodos', models.IntegerField()),
                ('cant_transacc', models.IntegerField()),
                ('sum_valpos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cod_per', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombres')),
                ('imagen', models.CharField(blank=True, max_length=200, verbose_name='Imagen de Perfil')),
                ('fecha_nac', models.DateField(null=True, verbose_name='Fecha de Nacimiento')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Direccion')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('cod_comunidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BDmscv.comunidad')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('cod_rep', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_act', models.DateField(blank=True, null=True, verbose_name='Fecha cuando se recibio el item')),
                ('acta_reu', models.FileField(blank=True, null=True, upload_to='reporte_files/', verbose_name='Acta de reunion')),
                ('nom_partici', models.CharField(max_length=1000, verbose_name='Participantes')),
                ('img_act', models.ImageField(blank=True, null=True, upload_to='img_act/', verbose_name='Imagen de la Actividad')),
                ('desc_act', models.CharField(max_length=1000, verbose_name='Descripción de la Actividad')),
                ('cod_per', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BDmscv.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Modulo_Comp',
            fields=[
                ('cod_mo_com', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_mod', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Modulo')),
                ('fecha_ini', models.DateField(null=True, verbose_name='Fecha de Inicio')),
                ('fecha_ter', models.DateField(null=True, verbose_name='Fecha de Termino')),
                ('Categoria', models.CharField(blank=True, max_length=200, null=True, verbose_name='Categoria')),
                ('recompensa', models.FloatField(verbose_name='Recompensa pagada')),
                ('cod_per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDmscv.persona')),
            ],
        ),
        migrations.CreateModel(
            name='AuthPago',
            fields=[
                ('cod_authpay', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_auth', models.DateField(auto_now_add=True, verbose_name='Fecha de autorizacion')),
                ('per_auth1', models.CharField(max_length=20, verbose_name='Id de la persona que autoriza 1')),
                ('per_auth2', models.CharField(max_length=20, verbose_name='Id de la persona que autoriza 2')),
                ('auth_1', models.BooleanField(default=False, verbose_name='Autorizacion 1')),
                ('auth_2', models.BooleanField(default=False, verbose_name='Autorizacion 2')),
                ('cod_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BDmscv.reporte')),
            ],
        ),
    ]
