# Generated by Django 3.1.1 on 2021-05-26 18:08

from django.db import migrations, models
import django.db.models.deletion
import s3direct.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agradecimiento',
            fields=[
                ('cod_recom', models.BigAutoField(primary_key=True, serialize=False)),
                ('cod_per', models.CharField(max_length=50, verbose_name='Codigo de la Persona')),
                ('nom_per_agre', models.CharField(max_length=100, verbose_name='Nombre de quien recibe el agradecimiento')),
                ('from_cuenta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cuenta proveniente')),
                ('fecha_agre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha de agradecimiento')),
                ('descrip_pago', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripcion del pago')),
                ('amount', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cantidad depositada')),
                ('id_transacc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Id de la Transaccion')),
            ],
        ),
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('cod_comunidad', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom_comunidad', models.CharField(max_length=100, verbose_name='Nombre de la comunidad')),
                ('descrip', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripcion')),
                ('fecha_creacion', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de creacion')),
                ('hubi_comuni', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hubicacion de la Comunidad ')),
                ('coor_comuni', models.CharField(blank=True, max_length=100, null=True, verbose_name='Coordenadas para google maps')),
                ('image_co', models.CharField(blank=True, default='static/img/Comunidad-online.png', max_length=500, null=True, verbose_name='Imagen de referencia')),
                ('is_active', models.BooleanField(default=False, verbose_name='¿Esta activo?')),
            ],
        ),
        migrations.CreateModel(
            name='data',
            fields=[
                ('id_data', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_add', models.CharField(max_length=50, verbose_name='Fecha de registro')),
                ('cant_usuarios', models.IntegerField()),
                ('cant_nodos', models.IntegerField()),
                ('cant_transacc', models.IntegerField()),
                ('sum_valpos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cod_per', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombres')),
                ('imagen', models.CharField(blank=True, max_length=200, verbose_name='Imagen de Perfil')),
                ('fecha_nac', models.DateField(null=True, verbose_name='Fecha de Nacimiento')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Direccion')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('cod_comunidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BDmscv.comunidad')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('cod_rep', models.BigAutoField(primary_key=True, serialize=False)),
                ('cant_valpos', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de Valpos')),
                ('fecha_act', models.DateField(blank=True, null=True, verbose_name='Fecha de realizacion de la actividad comunitaria')),
                ('nom_act', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre de la actividad')),
                ('nom_partici', models.CharField(max_length=1000, verbose_name='Participantes')),
                ('desc_act', models.CharField(max_length=1000, verbose_name='Descripción de la Actividad')),
                ('report_image', s3direct.fields.S3DirectField(blank=True)),
                ('report_video', s3direct.fields.S3DirectField(blank=True)),
                ('report_files', s3direct.fields.S3DirectField(blank=True)),
                ('cod_per', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BDmscv.persona', verbose_name='Nombre de quien hizo el reporte')),
            ],
        ),
        migrations.CreateModel(
            name='Modulo_Comp',
            fields=[
                ('cod_mo_com', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_mod', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Modulo')),
                ('fecha_ini', models.DateField(null=True, verbose_name='Fecha de Inicio')),
                ('fecha_ter', models.DateField(null=True, verbose_name='Fecha de Termino')),
                ('Categoria', models.CharField(blank=True, max_length=200, null=True, verbose_name='Categoria')),
                ('recompensa', models.FloatField(verbose_name='Recompensa pagada')),
                ('cod_per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDmscv.persona')),
            ],
        ),
        migrations.CreateModel(
            name='AuthPago',
            fields=[
                ('cod_authpay', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_auth1', models.DateField(blank=True, null=True, verbose_name='Fecha de la primera autorizacion')),
                ('fecha_auth2', models.DateField(blank=True, null=True, verbose_name='Fecha de la segunda autorizacion')),
                ('per_auth1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Id de la persona que autoriza 1')),
                ('per_auth2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Id de la persona que autoriza 2')),
                ('cod_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BDmscv.reporte')),
            ],
        ),
    ]
