# Generated by Django 3.2.3 on 2021-06-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDmscv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='report_files',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='report_image',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='report_video',
            field=models.FileField(upload_to=''),
        ),
    ]
