# Generated by Django 3.1.1 on 2021-01-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDmscv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='nom_act',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Titulo de la actividad'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='fecha_act',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha cuanse realizo la actividad comunitaria'),
        ),
    ]
