# Generated by Django 3.1.1 on 2020-10-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDmscv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunidad',
            name='id_com_cy',
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='cod_comunidad',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
