# Generated by Django 3.1.1 on 2020-10-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDmscv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='image_co',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de creacion'),
        ),
    ]
