# Generated by Django 3.1.1 on 2020-10-26 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BDmscv', '0002_auto_20201024_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='cod_per',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
