# Generated by Django 3.2.3 on 2021-06-03 22:37

import MSCValpo.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDmscv', '0002_auto_20210603_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='report_files',
            field=models.FileField(storage=MSCValpo.storage_backends.PublicFilesStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='report_image',
            field=models.FileField(storage=MSCValpo.storage_backends.PublicImagesStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='report_video',
            field=models.FileField(storage=MSCValpo.storage_backends.PublicVideosStorage(), upload_to=''),
        ),
    ]
