# Generated by Django 3.1.1 on 2021-01-05 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BDmscv', '0002_auto_20210102_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authpago',
            name='auth_1',
        ),
        migrations.RemoveField(
            model_name='authpago',
            name='auth_2',
        ),
        migrations.AlterField(
            model_name='authpago',
            name='fecha_auth',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de autorizacion'),
        ),
        migrations.AlterField(
            model_name='authpago',
            name='per_auth1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Id de la persona que autoriza 1'),
        ),
        migrations.AlterField(
            model_name='authpago',
            name='per_auth2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Id de la persona que autoriza 2'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='cod_per',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BDmscv.persona', verbose_name='Nombre de quien hizo el reporte'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='fecha_act',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de realizacion de la actividad comunitaria'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='nom_act',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre de la actividad'),
        ),
    ]
