# Generated by Django 3.1.1 on 2020-10-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDmscv', '0003_auto_20201025_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id_data', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_add', models.DateField(auto_now_add=True)),
                ('cant_usuarios', models.IntegerField(max_length=500)),
                ('cant_nodos', models.IntegerField(max_length=500)),
                ('cant_transacc', models.IntegerField(max_length=500)),
                ('sum_valpos', models.IntegerField(max_length=500)),
            ],
        ),
    ]
