# Generated by Django 3.2.3 on 2021-06-08 00:58

import MSCValpo.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDmscv', '0003_auto_20210603_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='report_files',
        ),
        migrations.AlterField(
            model_name='reporte',
            name='report_image',
            field=models.FileField(storage=MSCValpo.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='report_video',
            field=models.FileField(storage=MSCValpo.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
