# Generated by Django 3.1.1 on 2021-01-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDmscv', '0003_auto_20210105_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authpago',
            name='fecha_auth',
        ),
        migrations.AddField(
            model_name='authpago',
            name='fecha_auth1',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de la primera autorizacion'),
        ),
        migrations.AddField(
            model_name='authpago',
            name='fecha_auth2',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de la segunda autorizacion'),
        ),
    ]
