# Generated by Django 3.1.1 on 2021-03-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDmscv', '0004_auto_20210108_1230'),
    ]

   
