# Generated by Django 3.1.1 on 2021-01-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDmscv', '0004_auto_20210108_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='fecha_add',
            field=models.DateField(verbose_name='Fecha de registro'),
        ),
    ]
