# Generated by Django 3.1.1 on 2021-03-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDmscv', '0005_auto_20210307_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='cant_valpos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad de Valpos'),
        ),
    ]
