# Generated by Django 3.2.3 on 2021-06-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDmscv', '0005_rename_report_video_reporte_report_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agradecimiento',
            name='descrip_pago',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripcion del pago'),
        ),
    ]
