# Generated by Django 3.1.1 on 2021-01-16 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDmscv', '0005_auto_20210112_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidad',
            name='image_co',
            field=models.CharField(blank=True, default='static/img/Comunidad-online.png', max_length=500, null=True, verbose_name='Imagen de referencia'),
        ),
    ]
