# Generated by Django 3.1.1 on 2021-01-23 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BDmscv', '0006_auto_20210115_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agradecimiento',
            fields=[
                ('cod_recom', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_per_re', models.CharField(max_length=100, verbose_name='Nombre de quien recibe el agradecimiento')),
                ('cuenta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cuenta proveniente')),
                ('fecha_recom', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha de agradecimiento')),
                ('descrip_pago', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripcion del pago')),
                ('amount', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cantidad depositada')),
                ('id_transacc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Id de la Transaccion')),
                ('cod_per', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BDmscv.persona')),
            ],
        ),
    ]
