# Generated by Django 3.1.1 on 2021-01-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BDmscv', '0007_agradecimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agradecimiento',
            old_name='fecha_recom',
            new_name='fecha_agre',
        ),
        migrations.RenameField(
            model_name='agradecimiento',
            old_name='cuenta',
            new_name='from_cuenta',
        ),
        migrations.RenameField(
            model_name='agradecimiento',
            old_name='nom_per_re',
            new_name='nom_per_agre',
        ),
    ]
