# Generated by Django 3.1.1 on 2021-01-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDmscv', '0008_auto_20210124_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agradecimiento',
            name='cod_per',
            field=models.CharField(default=1, max_length=50, verbose_name=''),
            preserve_default=False,
        ),
    ]
