# Generated by Django 3.1.1 on 2021-04-15 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BDmscv', '0009_auto_20210124_1817'),
        ('BDmscv', '0006_reporte_cant_valpos'),
    ]

    operations = [
    ]
