# Generated by Django 3.1.1 on 2020-09-22 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('cod_per', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electronico')),
                ('Rut', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombres')),
                ('apellido', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellidos')),
                ('imgen', models.ImageField(blank=True, max_length=200, null=True, upload_to='perfil/', verbose_name='Imagen de Perfil')),
                ('fecha_nac', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Direccion')),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('cod_comunidad', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_comunidad', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateField()),
                ('fecha_ter', models.DateField(blank=True, null=True)),
                ('hubi_comuni', models.CharField(max_length=30)),
                ('coor_comuni', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('cod_rol', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_ele_rol', models.DateField()),
                ('fecha_ter_rol', models.DateField()),
                ('cod_per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('cod_item', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_item', models.CharField(max_length=30)),
                ('fecha_recib', models.DateField()),
                ('img_item', models.ImageField(upload_to='')),
                ('cod_comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.comunidad')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('cod_evento', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_evento', models.CharField(max_length=30)),
                ('hubi_eve', models.CharField(max_length=60)),
                ('coor_eve', models.IntegerField()),
                ('fecha_crea_eve', models.DateField(auto_now=True)),
                ('fecha_reali_eve', models.DateField()),
                ('cod_comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.comunidad')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='cod_comunidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.comunidad'),
        ),
    ]
